<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NC003" name="testcases.mips.TC_PracticeReSubmissionSingleTin" tests="44" failures="13" timestamp="28 Mar 2018 19:18:45 GMT" time="7285.971" errors="0">
  <testcase name="TC_AllMeasures" time="204.420" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="100.400" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="198.252" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="200.666" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="195.820" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="164.505" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="159.208" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="101.274" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="132.171" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="218.285" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="164.186" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="160.061" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="118.482" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="430.412" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 29	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 29	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="163.371" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="201.842" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="165.883" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="115.635" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="156.264" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="229.020" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="158.770" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="101.297" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="202.379" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="158.336" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="97.470" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="105.814" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="97.260" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="216.863" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="96.273" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="196.151" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="201.706" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="93.477" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="162.861" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="99.775" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="161.658" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="206.480" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="215.857" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="203.136" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="92.907" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="200.314" classname="testcases.mips.TC_PracticeReSubmissionSingleTin">
    <failure type="java.lang.AssertionError" message="Step 16	Action: verifyelement	Status: Fail">
      <![CDATA[java.lang.AssertionError: Step 16	Action: verifyelement	Status: Fail
	at org.testng.Assert.fail(Assert.java:94)
	at buisness.frameworkengine.TestExecutor.testexecute(TestExecutor.java:336)
	at testcases.mips.TC_PracticeReSubmissionSingleTin.TC_AllMeasures(TC_PracticeReSubmissionSingleTin.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at TestNGLoader.Loader.main(Loader.java:60)
]]>
    </failure>
  </testcase> <!-- TC_AllMeasures -->
  <testcase name="TC_AllMeasures" time="150.182" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="97.958" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="159.770" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
  <testcase name="TC_AllMeasures" time="229.120" classname="testcases.mips.TC_PracticeReSubmissionSingleTin"/>
</testsuite> <!-- testcases.mips.TC_PracticeReSubmissionSingleTin -->
